name: CI

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: install packages
        run: |
          sudo apt install -y nodejs npm awscli
          sudo npm i -g pnpm

      - name: install node dependencies
        run: |
          cd $GITHUB_WORKSPACE
          pnpm i

      - name: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        run: |
          pnpm run deploy
